name: sports_talent_assessment
description: AI-powered sports talent assessment platform for athletes across India

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter
  
  # UI & Design
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.0
  shimmer: ^3.0.0
  lottie: ^3.3.1
  glassmorphism: ^3.0.0
  
  # Navigation & State Management
  go_router: ^16.2.1
  provider: ^6.1.1
  riverpod: ^2.5.1
  flutter_riverpod: ^2.5.1
  
  # Backend & Authentication
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.3
  shared_preferences: ^2.2.2
  
  # Data & Models
  equatable: ^2.0.5
  json_annotation: ^4.8.1
  
  # Sensors & Camera
  camera: ^0.11.2
  sensors_plus: ^7.0.0
  permission_handler: ^12.0.1
  
  # Charts & Visualization
  fl_chart: ^0.69.0
  syncfusion_flutter_charts: ^31.1.19
  
  # Animations & Effects
  flutter_animate: ^4.3.0
  rive: ^0.13.20
  
  # Utilities
  intl: ^0.20.2
  uuid: ^4.2.1
  connectivity_plus: ^7.0.0
  device_info_plus: ^11.5.0
  package_info_plus: ^9.0.0
  url_launcher: ^6.2.2
  image_picker: ^1.0.5
  
  # Haptic Feedback
  vibration: ^3.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.7

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/animations/
    - assets/icons/
    - assets/3d_models/
  
  # fonts:
  #   - family: Inter
  #     fonts:
  #       - asset: assets/fonts/Inter-Regular.ttf
  #       - asset: assets/fonts/Inter-Medium.ttf
  #         weight: 500
  #       - asset: assets/fonts/Inter-SemiBold.ttf
  #         weight: 600
  #       - asset: assets/fonts/Inter-Bold.ttf
  #         weight: 700