// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6EPCOE8Givh1NawqzKDmMkcUhdI_bq2k',
    appId: '1:353205052706:web:c2eaf7b4ea7fba3b32317b',
    messagingSenderId: '353205052706',
    projectId: 'ai-sport-assessment',
    authDomain: 'ai-sport-assessment.firebaseapp.com',
    storageBucket: 'ai-sport-assessment.firebasestorage.app',
    measurementId: 'G-7NF803DB73',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPifHu945t_OZ9HkFkLW9hlHRyFRy8Kug',
    appId: '1:353205052706:android:5815e7b99f14911b32317b',
    messagingSenderId: '353205052706',
    projectId: 'ai-sport-assessment',
    storageBucket: 'ai-sport-assessment.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnnoi2EizFzSupFC-KdD_aTd_ngwJSE3s',
    appId: '1:353205052706:ios:0583239a9b09ef7f32317b',
    messagingSenderId: '353205052706',
    projectId: 'ai-sport-assessment',
    storageBucket: 'ai-sport-assessment.firebasestorage.app',
    iosClientId: '353205052706-4gq8s4kqbujo56bdd2gp51jd7gl605iu.apps.googleusercontent.com',
    iosBundleId: 'com.aisport.app',
  );
}
